// city (lowercase) → accepted country names (lowercase)
export const CITY_COUNTRIES: Record<string, string[]> = {
  "lagos":          ["nigeria"],
  "abuja":          ["nigeria"],
  "kano":           ["nigeria"],
  "ibadan":         ["nigeria"],
  "port harcourt":  ["nigeria"],
  "london":         ["united kingdom", "uk", "england", "great britain"],
  "manchester":     ["united kingdom", "uk", "england"],
  "birmingham":     ["united kingdom", "uk", "england"],
  "leeds":          ["united kingdom", "uk", "england"],
  "glasgow":        ["united kingdom", "uk", "scotland"],
  "edinburgh":      ["united kingdom", "uk", "scotland"],
  "new york":       ["united states", "usa", "us", "america"],
  "los angeles":    ["united states", "usa", "us", "america"],
  "chicago":        ["united states", "usa", "us", "america"],
  "houston":        ["united states", "usa", "us", "america"],
  "miami":          ["united states", "usa", "us", "america"],
  "atlanta":        ["united states", "usa", "us", "america"],
  "dubai":          ["united arab emirates", "uae"],
  "abu dhabi":      ["united arab emirates", "uae"],
  "accra":          ["ghana"],
  "kumasi":         ["ghana"],
  "nairobi":        ["kenya"],
  "mombasa":        ["kenya"],
  "johannesburg":   ["south africa"],
  "cape town":      ["south africa"],
  "durban":         ["south africa"],
  "toronto":        ["canada"],
  "vancouver":      ["canada"],
  "montreal":       ["canada"],
  "calgary":        ["canada"],
  "paris":          ["france"],
  "berlin":         ["germany"],
  "frankfurt":      ["germany"],
  "munich":         ["germany"],
  "madrid":         ["spain"],
  "barcelona":      ["spain"],
  "rome":           ["italy"],
  "milan":          ["italy"],
  "amsterdam":      ["netherlands"],
  "brussels":       ["belgium"],
  "zurich":         ["switzerland"],
  "geneva":         ["switzerland"],
  "lisbon":         ["portugal"],
  "stockholm":      ["sweden"],
  "oslo":           ["norway"],
  "copenhagen":     ["denmark"],
  "helsinki":       ["finland"],
  "dublin":         ["ireland"],
  "sydney":         ["australia"],
  "melbourne":      ["australia"],
  "brisbane":       ["australia"],
  "perth":          ["australia"],
  "auckland":       ["new zealand"],
  "singapore":      ["singapore"],
  "hong kong":      ["hong kong"],
  "beijing":        ["china"],
  "shanghai":       ["china"],
  "guangzhou":      ["china"],
  "shenzhen":       ["china"],
  "tokyo":          ["japan"],
  "osaka":          ["japan"],
  "seoul":          ["south korea"],
  "mumbai":         ["india"],
  "delhi":          ["india"],
  "new delhi":      ["india"],
  "bangalore":      ["india"],
  "chennai":        ["india"],
  "kolkata":        ["india"],
  "karachi":        ["pakistan"],
  "lahore":         ["pakistan"],
  "islamabad":      ["pakistan"],
  "dhaka":          ["bangladesh"],
  "colombo":        ["sri lanka"],
  "kathmandu":      ["nepal"],
  "cairo":          ["egypt"],
  "casablanca":     ["morocco"],
  "dakar":          ["senegal"],
  "abidjan":        ["ivory coast", "côte d'ivoire"],
  "addis ababa":    ["ethiopia"],
  "dar es salaam":  ["tanzania"],
  "kampala":        ["uganda"],
  "lusaka":         ["zambia"],
  "harare":         ["zimbabwe"],
  "luanda":         ["angola"],
  "kinshasa":       ["democratic republic of congo", "drc"],
  "mexico city":    ["mexico"],
  "são paulo":      ["brazil"],
  "sao paulo":      ["brazil"],
  "rio de janeiro": ["brazil"],
  "buenos aires":   ["argentina"],
  "bogotá":         ["colombia"],
  "bogota":         ["colombia"],
  "lima":           ["peru"],
  "santiago":       ["chile"],
  "riyadh":         ["saudi arabia"],
  "jeddah":         ["saudi arabia"],
  "doha":           ["qatar"],
  "kuwait city":    ["kuwait"],
  "manama":         ["bahrain"],
  "muscat":         ["oman"],
  "istanbul":       ["turkey"],
  "ankara":         ["turkey"],
  "athens":         ["greece"],
  "warsaw":         ["poland"],
  "prague":         ["czech republic", "czechia"],
  "budapest":       ["hungary"],
  "bucharest":      ["romania"],
  "kyiv":           ["ukraine"],
  "moscow":         ["russia"],
};

export function checkCityCountry(city: string, country: string): boolean {
  const c = city.trim().toLowerCase();
  const n = country.trim().toLowerCase();
  if (!c || !n) return true;
  const validCountries = CITY_COUNTRIES[c];
  if (!validCountries) return true; // unknown city — don't warn
  return validCountries.some(v => n.includes(v) || v.includes(n));
}
